config/routes.rb
NflDraft::Application.routes.draw do

  get 'welcome/index'
  root 'welcome#index'

  get '/players/available', to: 'players#available' # Show available players
  get '/results/round/:round', to: 'results#round' # Results for each round
  get '/results/all', to: 'results#all' # All Results
  post '/teams/acquire', to: 'teams#acquire' # Draft players

  resources :teams do
    get '/teams', to: 'teams#index' # Index
    get '/teams/:id', to: 'teams#show' # Show
  end

  resources :results do
    get '/results', to: 'results#index' # Index
  end
  
  resources :players do
    get '/players', to: 'players#index' # Index 
    get '/players/:id', to: 'players#show' # Show
  end

end

app/models/draft.rb
class Draft < ActiveRecord::Base
	# Relations
	belongs_to :player
	belongs_to :team

	# Validations
	validates_presence_of :round, :pick, :team_id

	def self.latest
		not_drafted = self.where(:player_id => nil).first
		if not_drafted
			return not_drafted
		else
			return false
		end
	end

	def self.last_three
		drafted = Draft.all.keep_if { |d| d if d.player }
		if drafted
			return drafted.last(3)
		else
			return false
		end
	end

	def acquire(player_id, team_id)
		player = Player.find(player_id)
		latest = self.class.latest
		if team_id.to_i == latest.team.id
			player.draft = latest
			return player.save!
		else
			return false
		end
	end
end

app/models/player.rb
class Player < ActiveRecord::Base
	# Relations
	has_one :draft
	has_one :team, through: :draft

	# Validations
	validates_presence_of :name
	#validates_uniqueness_of :name

	def self.available
		players = Player.all.delete_if { |p| p if p.team }
		if players
			return players
		else
			return false
		end
	end
end

app/models/team.rb
class Team < ActiveRecord::Base
	# Relations
	has_many :drafts
	has_many :players, through: :drafts

	# Validations
	validates_presence_of :name, :division
	#validates_uniqueness_of :name

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
	def index
		@players = Player.all
		@draft = Draft.latest
	end

	def show
		if params[:id]
			@player = Player.find(params[:id])
		end
	end

	# List Available Players
	def available
		@players = Player.available
		@draft = Draft.latest
	end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
	# View Last 3 Drafts
	def index
		@drafts = Draft.last_three
		@next = Draft.latest
	end

	# View by Round
	def round
		if params[:round]
			@drafts = Draft.where(:round => params[:round])

			# Need to add a redirect here for bad requests
		end
	end

	# View All
	def all
		@drafts = Draft.all
	end

end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
	def index
		@teams = Team.all
	end

	def show
		@team = Team.find(params[:id])
		@players = @team.players
	end

	def acquire
		if request.post?
			# Player AND Team are passed to catch simultaneous post errors
			if Draft.latest.acquire(params[:player_id], params[:team_id])
				flash[:success] = "Draft was successful"
				redirect_to players_url
			else
				flash[:warning] = "An error occurred"
				redirect_to players_url
			end
		else
			render text: "Error with post"
		end
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NFL Draft - By Herman Singh</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/libs/_nav.html.erb
<div class="row">
	<ul class="nav nav-pills">
		<!-- Home -->
		<li class="<%= 'active' if params[:controller] == 'welcome' %>">
			<%= link_to "Home", root_path %>
		</li>

		<!-- Teams -->
		<li class="<%= 'active' if params[:controller] == 'teams' %>">
			<%= link_to "Teams", teams_path %>
		</li>
		
		<!-- Players -->
		<li class="dropdown <%= 'active' if params[:controller] == 'players' %>">
		    <a class="dropdown-toggle"
		       data-toggle="dropdown"
		       href="#">Players
		        <b class="caret"></b>
		    </a>
		    <ul class="dropdown-menu">
		    	<li><a href="/players/available">Available</a></li>
		    	<li><a href="/players/">All Players</a></li>
		    </ul>
		</li>

		<!-- Results -->
		<li class="dropdown <%= 'active' if params[:controller] == 'results' %>">
		    <a class="dropdown-toggle"
		       data-toggle="dropdown"
		       href="#">Results
		        <b class="caret"></b>
		    </a>
		    <ul class="dropdown-menu">
		    	<li><a href="/results/">Latest</a></li>
		    	<li><a href="/results/round/1">Round 1</a></li>
		    	<li><a href="/results/round/2">Round 2</a></li>
		    	<li><a href="/results/round/3">Round 3</a></li>
		    	<li><a href="/results/round/4">Round 4</a></li>
		    	<li><a href="/results/round/5">Round 5</a></li>
		    	<li><a href="/results/round/6">Round 6</a></li>
		    	<li><a href="/results/round/7">Round 7</a></li>
		    	<li><a href="/results/all">All Results</a></li>
		    </ul>
		</li>
	</ul>
</div>

app/views/players/available.html.erb
<div class="container">
	<%= render "/libs/nav" %>
	<table class="table">
		<tr>
			<td>id</td>
			<td>Player Name</td>
			<td>Position</td>
			<td>Team</td>
		</tr>
		<% @players.each do |player| %>
			<% if player.team %>
				<tr class="success">
					<td><%= player.id %></td>
					<td><%= link_to player.name, player %></td>
					<td><%= player.position %></td>
					<td><%= link_to player.team.name, player.team %></td>
				</tr>
			<% else %>
				<tr class="warning">
					<td><%= player.id %></td>
					<td><%= link_to player.name, player %></td>
					<td><%= player.position %></td>
					<td>
					<% if @draft %>
						<%= form_tag("/teams/acquire", method: "post") do %>
							
								<%= hidden_field_tag(:team_id, @draft.team.id) %>
								<%= hidden_field_tag(:player_id, player.id) %>
								<%= submit_tag "Acquire to %s" % [@draft.team.name], :class => "btn btn-success" %>
						<% end %>
					<% else %>
						<i>Not drafted...</i>
					<% end %>
					</td>
				</tr>
			<% end %>
		<% end %>
	</table>
</div>

app/views/players/index.html.erb
<div class="container">
	<%= render "/libs/nav" %>
	<table class="table">
		<tr>
			<td>id</td>
			<td>Player Name</td>
			<td>Position</td>
			<td>Team</td>
		</tr>
		<% @players.each do |player| %>
			<% if player.team %>
				<tr class="success">
					<td><%= player.id %></td>
					<td><%= link_to player.name, player %></td>
					<td><%= player.position %></td>
					<td><%= link_to player.team.name, player.team %></td>
				</tr>
			<% else %>
				<tr class="warning">
					<td><%= player.id %></td>
					<td><%= link_to player.name, player %></td>
					<td><%= player.position %></td>
					<td>
					<% if @draft %>
						<%= form_tag("/teams/acquire", method: "post") do %>
							
								<%= hidden_field_tag(:team_id, @draft.team.id) %>
								<%= hidden_field_tag(:player_id, player.id) %>
								<%= submit_tag "Acquire to %s" % [@draft.team.name], :class => "btn btn-success" %>
						<% end %>
					<% else %>
						<i>Not drafted...</i>
					<% end %>
					</td>
				</tr>
			<% end %>
		<% end %>
	</table>
</div>

app/views/players/show.html.erb
<div class="container">
	<%= render "/libs/nav" %>
	<table class="table">
		<tr>
			<td>id</td>
			<td>Player Name</td>
			<td>Position</td>
			<td>Team</td>
		</tr>
		<% if @player.team %>
			<tr class="success">
		<% else %>
			<tr class="warning">
		<% end %>
			<td><%= @player.id %></td>
			<td><%= link_to @player.name, @player %></td>
			<td><%= @player.position %></td>
		<% if @player.team %>
			<td><%= link_to @player.team.name, @player.team %></td>
		<% else %>
			<td><i>Not yet drafted</i></td>
		<% end %>
		</tr>
	</table>
</div>

app/views/results/all.html.erb
<div class="container">
	<%= render "/libs/nav" %>
	<table class="table">
		<tr>
			<td>id</td>
			<td>Round</td>
			<td>Pick</td>
			<td>Player Name</td>
			<td>Team Name</td>
		</tr>
		<% @drafts.each do |draft| %>
			<% if draft.player %>
				<tr class="success">
			<% else %>
				<tr class="warning">
			<% end %>
					<td><%= draft.id %></td>
					<td><%= draft.round %></td>
					<td><%= draft.pick %></td>
					<% if draft.player %>
						<td><%= draft.player.name %></td>
					<% else %>
						<td><i>Pending...</i></td>
					<% end %>
					<td><%= link_to draft.team.name, draft.team %></td>
				</tr>
		<% end %>
	</table>
</div>

app/views/results/index.html.erb
<div class="container">
	<%= render "/libs/nav" %>
	<table class="table">
		<tr>
			<td>id</td>
			<td>Round</td>
			<td>Pick</td>
			<td>Player Name</td>
			<td>Team Name</td>
		</tr>
		<% if @drafts %>
			<% @drafts.each do |draft| %>
				<% if draft.player %>
					<tr class="success">
				<% else %>
					<tr class="warning">
				<% end %>
						<td><%= draft.id %></td>
						<td><%= draft.round %></td>
						<td><%= draft.pick %></td>
						<% if draft.player %>
							<td><%= draft.player.name %></td>
						<% else %>
							<td><i>Pending...</i></td>
						<% end %>
						<td><%= link_to draft.team.name, draft.team %></td>
					</tr>
			<% end %>
		<% end %>
	</table>
	<% if @next %>
		<div class="row">
			<div class="alert alert-info">
				<p><b>The draft is currently in Round <%= @next.round %>, Pick <%= @next.pick %> waiting for <%= @next.team.name %> to select a player</b></p>
			</div>
		</div>
	<% else @drafts %>
		<div class="row">
			<div class="alert alert-success">
				<p><b>The draft is complete.</b></p>
			</div>
		</div>
	<% end %>
</div>

app/views/results/round.html.erb
<div class="container">
	<%= render "/libs/nav" %>
	<table class="table">
		<tr>
			<td>id</td>
			<td>Round</td>
			<td>Pick</td>
			<td>Player Name</td>
			<td>Team Name</td>
		</tr>
		<% @drafts.each do |draft| %>
			<% player = draft.player %>
			<% if player %>
				<tr class="success">
			<% else %>
				<tr class="warning">
			<% end %>
					<td><%= draft.id %></td>
					<td><%= draft.round %></td>
					<td><%= draft.pick %></td>
					<% if player %>
						<td><%= player.name %></td>
					<% else %>
						<td><i>Pending...</i></td>
					<% end %>
					<td><%= link_to draft.team.name, draft.team %></td>
				</tr>
		<% end %>
	</table>
</div>

app/views/welcome/index.html.erb
<div class="container">
	<%= render "/libs/nav" %>
	<div class="row">
		<h1>NFL Draft App</h1>
		<p><i>by Herman Singh</i></p>
	</div>
</div>